### ISSUE TITLE
Allow comments in project file

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/rojo#207]
Project files in Rojo are complicated. We can make them nicer with comments.

We could:
- use an ad hoc superset of JSON with comments
- use JSON 5, which has poor library support, sadly
- use YAML, which allows deep nesting like TOML, but has a huge spec

**Comment by Kampfkarren** [comment]
Could do a weird hack where we filter out lines of just comments before giving it to Serde? 🤷‍♂

**Comment by LPGhatguy** [comment]
Projects in other formats could be supported in parallel to JSON!

TOML:

```toml
name = "Sisyphus Simulator"

[tree]
"$className" = "DataModel"

  [tree.HttpService]
  "$className" = "HttpService"

    [tree.HttpService."$properties"]
    HttpEnabled = true

  [tree.ReplicatedStorage]
  "$className" = "ReplicatedStorage"
  "$path" = "src/ReplicatedStorage"

  [tree.StarterPlayer]
  "$className" = "StarterPlayer"

    [tree.StarterPlayer.StarterPlayerScripts]
    "$className" = "StarterPlayerScripts"
    "$path" = "src/StarterPlayerScripts"

  [tree.Workspace]
  "$className" = "Workspace"

    [tree.Workspace."$properties"]
    Gravity = 67.3

    [tree.Workspace.Terrain]
    "$path" = "Terrain.rbxm"
```

YAML:

```yaml
name: Sisyphus Simulator
tree:
  $className: DataModel
  HttpService:
    $className: HttpService
    $properties:
      HttpEnabled: true
  ReplicatedStorage:
    $className: ReplicatedStorage
    $path: src/ReplicatedStorage
  StarterPlayer:
    $className: StarterPlayer
    StarterPlayerScripts:
      $className: StarterPlayerScripts
      $path: src/StarterPlayerScripts
  Workspace:
    $className: Workspace
    $properties:
      Gravity: 67.3
    Terrain:
      $path: Terrain.rbxm
```
