### ISSUE TITLE
Multiple instances being created for a single folder

### ISSUE THREAD

**Issue by nodomw** [rojo-rbx/rojo#912]
could be related to #516?

I tried linking the wally packages folder to 'Packages' in ReplicatedStorage and it had made a gazillion duplicate instances of it. For good measure, I changed the folder's location to StarterPlayer and there too it did the same thing.

This happens both when I leave `$path` as the root folder 'Packages' and when I move it to src/Packages
![image](https://github.com/rojo-rbx/rojo/assets/47635446/f6e8fea7-18a8-4f14-88ff-d40aaadce9d8)

So far, my project is just an empty Rojo project with aftman and wally added in.

default.project.json
```json
"ReplicatedStorage": {
    "Common": {
        "$path": "src/shared"
    },
    "Packages": {
        "$path": "src/Packages"
    }
},
```

tooling versions
```
$ rojo -V
Rojo 7.4.1

$ aftman -V
aftman 0.2.7

$ wally -V
wally 0.3.2
```

aftman tools
```toml
[tools]
rojo = "rojo-rbx/rojo@7.4.1"
wally = "UpliftGames/wally@0.3.2"
stylua = "johnnymorganz/stylua@0.14.2"
selene = "kampfkarren/selene@0.27.1"
```

wally packages
```toml
[dependencies]
topbarplus = "1foreverhd/topbarplus@3.0.2"
fusion = "elttob/fusion@0.2.0"
```
